# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [11]:
class Book:
    def __init__(self, title, author, pages, price):
        self.title = title
        self.author = author
        self.pages = pages
        self._price = price

    def describe(self):
        print(f"{self.title} by {self.author}. {self.pages} pages, Costs ${self._price}")

    def get_price(self):
        return self._price
    
    def set_price(self, new_price):
        if type(new_price) in [int, float]:
            self._price = new_price
        else:
            print("Invalid price! Price must be numeric.")

In [12]:
b1 = Book("Practical Programming", "Gries, Campbell, Montojo", 383, 50)
b1.describe()

b2 = Book("Building a Career in Data Science", "Robinson, Nolis", 322, 40)
b2.describe()

Practical Programming by Gries, Campbell, Montojo. 383 pages, Costs $50
Building a Career in Data Science by Robinson, Nolis. 322 pages, Costs $40


In [29]:
b1.set_price(50)
b1.set_price("50 dollars")
b1.get_price()

Invalid price! Price must be numeric.


50

#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [41]:
class Phone:
    def __init__(self, model, id, name, brand, price):
        self._model = model
        self._id = id
        self._name = name
        self._brand = brand
        self._price = price

    ### Getters
    def get_model(self):
        return self._model

    def get_id(self):
        return self._id

    def get_name(self):
        return self._name

    def get_brand(self):
        return self._brand

    def get_price(self):
        return self._price
    
    ### Setters
    def set_model(self, new_model):
        self._model = new_model

    def set_id(self, new_id):
        self._id = new_id

    def set_name(self, new_name):
        self._name = new_name

    def set_brand(self, new_brand):
        self._brand = new_brand

    def set_price(self, new_price):
        # Checking if the value is numeric before updating
        if type(new_price) in [int, float]:
            self._price = new_price
        else:
            print("Invalid price! Price must be numeric.")

    def calculate_total(self, price, tax):
        # Calculates total by multiplying price by (1 + tax rate)
        total = price * (1 + tax)
        return round(total, 2)

In [43]:
phone1 = Phone("17 Pro Max", "ABC123", "iPhone", "Apple", 1500)
phone1.calculate_total(phone1.get_price(), 0.13)

1695.0

## Numpy

In [44]:
import numpy as np

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [54]:
matrix = np.array([0, 1, 2, 3, 4, 5])
matrix_reshaped = matrix.reshape(2, 3)
print(matrix)
print(matrix_reshaped)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [57]:
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 3. Create a 1D array filled with zeros and another filled with ones

In [61]:
zeros_array = np.zeros((1, 5))
ones_array = np.ones((1, 5))

print(zeros_array)
print(ones_array)

[[0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]]


#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [70]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [69]:
def reverse_array(arr):
    return arr[-1::-1]

reverse_array(arr)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [77]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

a_b_horizontal = np.hstack((a, b))

print(a_b_horizontal)

[1 2 3 4 5 6]


#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [83]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

a_add_b = a + b
print("a + b:", a_add_b)

a_times_b = a * b
print("a * b:", a_times_b)

a + b: [5 7 9]
a * b: [ 4 10 18]
